name       : flatpak-builder
version    : 1.0.1
release    : 6
source     :
    - https://github.com/flatpak/flatpak-builder/releases/download/1.0.1/flatpak-builder-1.0.1.tar.xz : 1c9185dba790caa453a8b1fce304b7666b0fbcf56df015b1ad71a5d92c92e306
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Tool to build flatpaks from source
description: |
    Flatpak-builder is a tool for building flatpaks from sources.
    See http://flatpak.org/ for more information.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libelf)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(yaml-0.1)
    - elfutils-devel
    - docbook-xml
    - xmlto
rundeps    :
    - ccache
    - bzr
    - elfutils
    - flatpak
    - git
    - patch
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
