name       : flatpak-builder
version    : 10.0.9
release    : 3
source     :
    - https://github.com/flatpak/flatpak-builder/releases/download/0.10.9/flatpak-builder-0.10.9.tar.xz : b8253b327d9901cf20a5a0167674377be192012b90bfdc62d54d1c8621cfdd2a
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Tool to build flatpaks from source
description: |
    Flatpak-builder is a tool for building flatpaks from sources.
    See http://flatpak.org/ for more information.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libelf)
    - pkgconfig(libsoup-2.4)
    - elfutils-devel
    - docbook-xml
    - libcap2-devel
    - xmlto
rundeps    :
    - ccache
    - bzr
    - elfutils
    - flatpak
    - git
    - patch
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
