name       : flatpak-builder
version    : 1.2.1
release    : 15
source     :
    - https://github.com/flatpak/flatpak-builder/releases/download/1.2.1/flatpak-builder-1.2.1.tar.xz : f4bc0c7dbff4b536545c17bd36e71b5e93c75f48d6bd95f662f22f90a2d2920b
license    : LGPL-2.1-or-later
component  : desktop
summary    : Tool to build flatpaks from source
description: |
    Flatpak-builder is a tool for building flatpaks from sources.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libelf)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(yaml-0.1)
    - elfutils-devel
    - docbook-xml
    - xmlto
rundeps    :
    - ccache
    - bzr
    - elfutils
    - flatpak
    - git
    - patch
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
