name       : flatpak-builder
version    : 1.0.14
release    : 14
source     :
    - https://github.com/flatpak/flatpak-builder/releases/download/1.0.14/flatpak-builder-1.0.14.tar.xz : 69b65af4f63804127518c545184f9dfc9a9358cdedaabef2b1e50623ae2b8d8b
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Tool to build flatpaks from source
description: |
    Flatpak-builder is a tool for building flatpaks from sources.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libelf)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(yaml-0.1)
    - elfutils-devel
    - docbook-xml
    - xmlto
rundeps    :
    - ccache
    - bzr
    - elfutils
    - flatpak
    - git
    - patch
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
