name       : flatpak-builder
version    : 0.10.4
release    : 1
source     :
    - https://github.com/flatpak/flatpak-builder/releases/download/0.10.4/flatpak-builder-0.10.4.tar.xz : 41187e043d47421e933999086ae2ee0e0acbac093e1f6b9e5cb5bd97d70f37cb
license    : LGPL-2.1
component  : desktop.util
summary    : Tool to build flatpaks from source
description: |
    Flatpak-builder is a tool for building flatpaks from sources.
    See http://flatpak.org/ for more information.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libelf)
    - pkgconfig(libsoup-2.4)
    - elfutils-devel
    - docbook-xml
    - libcap2-devel
    - xmlto
rundeps    :
    - bzr
    - elfutils
    - flatpak
    - git
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
