name       : flatpak-builder
version    : 1.2.2
release    : 17
source     :
    - https://github.com/flatpak/flatpak-builder/releases/download/1.2.2/flatpak-builder-1.2.2.tar.xz : 89fda68e537c1e9de02352690bd89c3217a729164558d35f35b08f79ad84e03e
license    : LGPL-2.1-or-later
component  : desktop
summary    : Tool to build flatpaks from source
description: |
    Flatpak-builder is a tool for building flatpaks from sources.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libelf)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(yaml-0.1)
    - elfutils-devel
    - docbook-xml
    - xmlto
rundeps    :
    - ccache
    - bzr
    - elfutils
    - flatpak
    - git
    - patch
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
