name       : flatpak-builder
version    : 1.0.0
release    : 5
source     :
    - https://github.com/flatpak/flatpak-builder/releases/download/1.0.0/flatpak-builder-1.0.0.tar.xz : 858a5b2204f569e47fb6cb57f28f7a0dab9d6f7a5a73a7c2688e23c61bf8567b
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Tool to build flatpaks from source
description: |
    Flatpak-builder is a tool for building flatpaks from sources.
    See http://flatpak.org/ for more information.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libelf)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(yaml-0.1)
    - elfutils-devel
    - docbook-xml
    - xmlto
rundeps    :
    - ccache
    - bzr
    - elfutils
    - flatpak
    - git
    - patch
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
